on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: windows-latest

    steps: 
      - name: 'Testing Github actions'
        run: pwd

        - name: 'Testing Printing'
        run: print Mahmoud
